# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8098
    context-path: /mly

# mysql
spring:
    application:
      name: mly-system
    # 环境 dev|test|prod
    profiles:
        active: prod
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    thymeleaf:
         mode: HTML
         cache: true  #测试环境建议关闭
    aop:
        proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
    resources:
         static-locations: classpath:/META-INF/resources/,classpath:/static/
    #spring boot admin
    boot:
        admin:
           client:
              prefer-ip: true
              enabled: true
           url: http://127.0.0.1:${server.port}${server.context-path}
           context-path: /admin

#    redis:
#        database: 0
#        host: localhost
#        port: 6379
#        password:      # 密码（默认为空）
#        timeout: 6000  # 连接超时时长（毫秒）
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5       # 连接池中的最小空闲连接


# Mybatis配置
#mybatis:
#    mapperLocations: classpath:mapper/**/*.xml
#    configLocation: classpath:mybatis.xml



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hfutonline.mly.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: -1
    #logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #call-setters-on-nulls: true
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    default-executor-type: reuse
    #return-instance-for-empty-row: true

management:
  security:
    enabled: false
  context-path: /admin

info: #定义各种额外的详情给服务端显示
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
api-doc:
  enable: true


